@Api_HostAddress = https://localhost:7116

### Register user as Mohamed
POST {{Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "displayName": "Mohamed Ehab",
  "email": "mohamed.ehab@test.com",
  "password": "P@ssword1#",
  "confirmPassword": "P@ssword1#"
}

###

### Register user as Ahmed
POST {{Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "displayName": "Ahmed Hassan",
  "email": "ahmed.hassan@test.com",
  "password": "P@ssword2#",
  "confirmPassword": "P@ssword2#"
}

###

### Register user as Omar
POST {{Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "displayName": "Omar Mohamed",
  "email": "omar.mohamed@test.com",
  "password": "P@ssword3#",
  "confirmPassword": "P@ssword3#"
}

###

### Register user as Youssef
POST {{Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "displayName": "Youssef Ali",
  "email": "youssef.ali@test.com",
  "password": "P@ssword4#",
  "confirmPassword": "P@ssword4#"
}

###

### Register user as Karim
POST {{Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "displayName": "Karim Mahmoud",
  "email": "karim.mahmoud@test.com",
  "password": "P@ssword5#",
  "confirmPassword": "P@ssword5#"
}

### Register user as Hossam
POST {{Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "displayName": "Karim Mahmoud",
  "email": "hossam.mahmoud@test.com",
  "password": "P@ssword6#",
  "confirmPassword": "P@ssword6#"
}